"""Stage a recorded session as demo playback media.

Demo mode needs video files on the rig plus a spec naming them. Doing that by
hand means picking the right files out of a session directory and hand-writing
YAML, which is easy to get subtly wrong: a missing camera, the wrong frame rate,
or a path that only resolves on one machine.

This copies the chosen session's per-camera videos to the demo directory and
writes the spec, then validates the result through the same loader the
application uses, so a spec that would fail at startup fails here instead.

    python scripts/stage_demo_media.py temp/2p_sessions/20260914_christie2P_session001
    python scripts/stage_demo_media.py <session> --dest ~/Autotrainer/demo
    python scripts/stage_demo_media.py <session> --cameras left right --dry-run

Nothing is overwritten unless --force is given.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional

import cv2

from autotrainer.core.configuration.demo_sources import (
    DEFAULT_DEMO_SOURCES_PATH,
    DemoSourcesError,
    load_demo_sources,
)

#: Camera names the spec accepts, in the order they are searched for.
KNOWN_CAMERAS = ("left", "right", "stimCam", "camera4", "camera5", "camera6")

def find_camera_videos(session: Path, cameras: List[str]) -> Dict[str, Path]:
    """Map camera name to its first recorded video part in the session.

    A recorded camera file looks like <session>_<camera>-0000.mp4 and may be
    split into several parts. Only the first part is staged: demo playback loops
    one file per camera rather than following a rotation.
    """
    found: Dict[str, Path] = {}
    for camera in cameras:
        candidates = sorted(session.glob(f"*_{camera}-*.mp4")) or \
            sorted(session.glob(f"*_{camera}.mp4"))
        if not candidates:
            continue
        found[camera] = candidates[0]
        if len(candidates) > 1:
            print(f"  note: {camera} is split into {len(candidates)} parts; staging "
                  f"only {candidates[0].name}, which is what playback will loop")
    return found


def video_fps(path: Path) -> Optional[float]:
    capture = cv2.VideoCapture(str(path))
    try:
        if not capture.isOpened():
            return None
        fps = float(capture.get(cv2.CAP_PROP_FPS))
        return fps if fps > 0 else None
    finally:
        capture.release()


def write_spec(spec_path: Path, fps: float, staged: Dict[str, Path], loop: bool) -> None:
    lines = [
        "# reachAQ demo playback sources.",
        "#",
        f"# Generated by scripts/stage_demo_media.py from a recorded session.",
        "# Regenerate rather than editing by hand, so the media and the spec stay",
        "# in step.",
        "",
        f"fps: {fps:g}",
        f"loop: {str(bool(loop)).lower()}",
        "",
        "cameras:",
    ]
    lines.extend(f"  {camera}: {path.as_posix()}" for camera, path in sorted(staged.items()))
    spec_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("session", type=Path,
                        help="recorded session directory to stage")
    parser.add_argument("--dest", type=Path, default=Path("~/Autotrainer/demo"),
                        help="where to copy the media (default: %(default)s)")
    parser.add_argument("--spec", type=Path, default=DEFAULT_DEMO_SOURCES_PATH,
                        help="spec file to write (default: %(default)s)")
    parser.add_argument("--cameras", nargs="+", default=None, metavar="NAME",
                        help=f"cameras to stage (default: whichever of "
                             f"{', '.join(KNOWN_CAMERAS)} the session has)")
    parser.add_argument("--fps", type=float, default=None,
                        help="playback rate (default: read from the source video)")
    parser.add_argument("--no-loop", action="store_true",
                        help="do not restart at frame 0 on reaching the end")
    parser.add_argument("--force", action="store_true",
                        help="overwrite media and spec that already exist")
    parser.add_argument("--dry-run", action="store_true",
                        help="report what would be staged, and copy nothing")
    args = parser.parse_args()

    session = args.session.expanduser()
    if not session.is_dir():
        print(f"error: not a session directory: {session}", file=sys.stderr)
        return 1

    cameras = args.cameras or list(KNOWN_CAMERAS)
    unknown = [c for c in cameras if c not in KNOWN_CAMERAS]
    if unknown:
        print(f"error: unknown camera name(s) {unknown}; "
              f"expected from {list(KNOWN_CAMERAS)}", file=sys.stderr)
        return 1

    print(f"session: {session}")
    found = find_camera_videos(session, cameras)
    if not found:
        print(f"error: no camera videos found in {session}", file=sys.stderr)
        print(f"       looked for *_<camera>-*.mp4 with camera in {cameras}",
              file=sys.stderr)
        return 1

    for camera, path in sorted(found.items()):
        size_mb = path.stat().st_size / (1024 * 1024)
        print(f"  {camera:<9} {path.name}  ({size_mb:.1f} MB)")

    missing = [c for c in cameras if c not in found]
    if missing:
        print(f"  not found, will be omitted: {missing}")
        print("  (a reach camera with no video is disabled for the demo run)")

    fps = args.fps
    if fps is None:
        primary = found.get("left") or next(iter(found.values()))
        fps = video_fps(primary)
        if fps is None:
            print("error: could not read the frame rate from the source video; "
                  "pass --fps", file=sys.stderr)
            return 1
        print(f"  frame rate read from {primary.name}: {fps:g}")

    dest = args.dest.expanduser()
    spec_path = args.spec.expanduser()

    if args.dry_run:
        print(f"\ndry run: would copy {len(found)} file(s) to {dest}")
        print(f"dry run: would write {spec_path}")
        return 0

    dest.mkdir(parents=True, exist_ok=True)
    staged: Dict[str, Path] = {}
    for camera, source in sorted(found.items()):
        target = dest / source.name
        if target.exists() and not args.force:
            print(f"  keeping existing {target.name} (pass --force to replace)")
        else:
            print(f"  copying {source.name} -> {target}")
            shutil.copy2(source, target)
        staged[camera] = target

    if spec_path.exists() and not args.force:
        print(f"\nerror: {spec_path} already exists; pass --force to replace it",
              file=sys.stderr)
        return 1

    spec_path.parent.mkdir(parents=True, exist_ok=True)
    write_spec(spec_path, fps, staged, loop=not args.no_loop)
    print(f"\nwrote {spec_path}")

    # Validate through the same loader the application uses, so a spec that
    # would fail at startup fails here instead.
    try:
        sources = load_demo_sources(spec_path)
    except DemoSourcesError as err:
        print(f"error: the spec just written does not load: {err}", file=sys.stderr)
        return 1

    print(f"validated: fps={sources.fps:g} loop={sources.loop} "
          f"cameras={sorted(sources.enabled_camera_names())}")
    print("\nNext: python scripts/verify_demo_readiness.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
